return {
    { 'Beast Killer', 4, 'Wild Oats, Sprout Smack, 1000 Needles' },
    { 'Auto Regen', 16, 'Sheep Song, Healing Breeze' },
    { 'Lizard Killer', 20, 'Foot Kick, Claw Cyclone, Ram Charge' },
    { 'Clear Mind', 24, 'Poison Breath, Soporific, Venom Shell, Awful Eye, Filamented Hold, Maelstrom, Feather Tickle, Sandspray, Warm-Up, Lowing, Mind Blast' },
    { 'Magic Accuracy', 28, 'Bomb Toss' },
    { 'Resist Sleep', 30, 'Pollen, Wild Carrot, Magic Fruit, Yawn, Exuviation' },
    { 'Magic Attack Bonus', 32, 'Cursed Sphere, Sound Blast, Eyes On Me, Memento Mori, Heat Breath, Magic Hammer, Reactor Cool, Blank Gaze' },
    { 'Undead Killer', 34, 'Bludgeon, Smite of Rage' },
    { 'Attack Bonus', 38, 'Battle Dance, Uppercut, Death Scissors, Spinal Cleave, Temporal Shift' },
    { 'Rapid Shot', 38, 'Feather Storm, Jet Stream, Hydro Shot' },
    { 'Max MP Boost', 40, 'Metallic Body, Mysterious Light, Hecatomb Wave' },
    { 'Defense Bonus', 40, 'Grand Slam, Terror Touch, Saline Coat, Vertical Cleave, Quad. Continuum' },
    { 'Plantoid Killer', 44, 'Power Attack, Mandibular Bite' },
    { 'Magic Defense Bonus', 50, 'Magnetite Cloud, Ice Break' },
    { 'Auto Refresh', 50, 'Cold Wave (1), Frightful Roar (2), Self-Destruct (2), Light of Penance (2), Voracious Trunk (3), Actinic Burst (4), Plasma Charge (4)' },
    { 'Max HP Boost', 62, 'Flying Hip Press, Body Slam, Frypan, Empty Trash' },
    { 'Accuracy Bonus', 63, 'Dimensional Death, Frenetic Rip, Disseverment, Vanity Dive' },
    { 'Conserve MP', 65, 'Chaotic Eye, Zephyr Mantle, Frost Breath, Firespit, Metallic Body, Blood Drain, Digest' },
    { 'Evasion Bonus', 69, 'Screwdriver, Hysteric Barrage, Occultation' },
    { 'Resist Gravity', 69, 'Feather Barrier' },
    { 'Store TP', 69, 'Sickle Slash, Tail Slap' },
    { 'Counter', 70, 'Enervation' },
    { 'Fast Cast', 72, 'Bad Breath, Auroral Drape' },
};
