return {
    { 'Beast Killer', 4, 'Wild Oats, Sprout Smack, 1000 Needles', { 2, 4, 6 } },
    { 'Auto Regen', 16, 'Sheep Song, Healing Breeze', { 2 } },
    { 'Lizard Killer', 20, 'Foot Kick, Claw Cyclone, Ram Charge', { 2, 4 } },
    { 'Clear Mind', 24, 'Poison Breath, Soporific, Venom Shell, Awful Eye, Filamented Hold, Maelstrom, Feather Tickle, Sandspray, Warm-Up, Lowing, Mind Blast', { 2, 4, 6, 8 } },
    { 'Magic Accuracy', 28, 'Bomb Toss', { 1 } },
    { 'Resist Sleep', 30, 'Pollen, Wild Carrot, Magic Fruit, Yawn, Exuviation', { 2, 4 } },
    { 'Magic Attack Bonus', 32, 'Cursed Sphere, Sound Blast, Eyes On Me, Memento Mori, Heat Breath, Magic Hammer, Reactor Cool, Blank Gaze', { 2, 4, 6, 8 } },
    { 'Undead Killer', 34, 'Bludgeon, Smite of Rage', { 2 } },
    { 'Attack Bonus', 38, 'Battle Dance, Uppercut, Death Scissors, Spinal Cleave, Temporal Shift', { 2, 4, 6, 8 } },
    { 'Rapid Shot', 38, 'Feather Storm, Jet Stream, Hydro Shot', { 2 } },
    { 'Max MP Boost', 40, 'Metallic Body, Mysterious Light, Hecatomb Wave', { 2, 4 } },
    { 'Defense Bonus', 40, 'Grand Slam, Terror Touch, Saline Coat, Vertical Cleave, Quad. Continuum', { 2, 4, 6, 8 } },
    { 'Plantoid Killer', 44, 'Power Attack, Mandibular Bite', { 2, 4 } },
    { 'Magic Defense Bonus', 50, 'Magnetite Cloud, Ice Break', { 2, 4, 6 } },
    { 'Auto Refresh', 50, 'Cold Wave (1), Frightful Roar (2), Self-Destruct (2), Light of Penance (2), Voracious Trunk (3), Actinic Burst (4), Plasma Charge (4)', { 2 } },
    { 'Max HP Boost', 62, 'Flying Hip Press, Body Slam, Frypan, Empty Trash', { 2, 4, 6, 8 } },
    { 'Accuracy Bonus', 63, 'Dimensional Death, Frenetic Rip, Disseverment, Vanity Dive', { 2, 4, 6, 8 } },
    { 'Conserve MP', 65, 'Chaotic Eye, Zephyr Mantle, Frost Breath, Firespit, Metallic Body, Blood Drain, Digest', { 2, 4, 6 } },
    { 'Evasion Bonus', 69, 'Screwdriver, Hysteric Barrage, Occultation', { 2, 4, 6 } },
    { 'Resist Gravity', 69, 'Feather Barrier', { 1 } },
    { 'Store TP', 69, 'Sickle Slash, Tail Slap', { 2, 4, 6 } },
    { 'Counter', 70, 'Enervation', { 1 } },
    { 'Fast Cast', 72, 'Bad Breath, Auroral Drape', { 2, 4, 6 } },
};
